### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by BenWeekes** [XRFoundation/UniversalVolumetric-Demo#2]
I ran the project using 

git clone https://github.com/XRFoundation/UniversalVolumetric-Demo
npm install
npm run build
npm run dev

I then access the page in a browser but there is an error from /node_modules/@xrfoundation/volumetric/dist/player.js
player.js:10 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at player.js:10:31

Is it intended to work out of the box?
What am I missing?
Thanks in advance

**Comment by mrhegemon** [comment]
Hi @BenWeekes 

This lib is going to go into active updates at the end of the mont.

We are moving everything over to .uvol

There are some small encoder and decoder updates incoming. We have just been slammed. 

Happy to talk to you on discord about our plans.

**Comment by mrhegemon** [comment]
Working now
